### ISSUE TITLE
docker-compose up doesn't work

### ISSUE THREAD

**Issue by adeelarifbhatti** [pferreir/indico-docker#1]
---> Running in 291b6532c586
Collecting indico==1.9.10.dev2 from https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl
  **HTTP error 404 while getting https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl**
  Could not install requirement indico==1.9.10.dev2 from https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl because of error 404 Client Error: Not Found for url: https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl
Could not install requirement indico==1.9.10.dev2 from https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl because of HTTP error 404 Client Error: Not Found for url: https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl for URL https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl
ERROR: Service 'indico-web' failed to build: The command '/bin/sh -c ${pip} install https://github.com/pferreir/indico/releases/download/1.9.10.dev2/indico-1.9.10.dev2-py2-none-any.whl' returned a non-zero code: 1

**Comment by Pixelartist** [comment]
+1 I have the same error

**Comment by pferreir** [comment]
Thanks for the report. I will actually delete this repo, since we've published an official one:

https://github.com/indico/indico-containers
